import { Command } from "./types";

export const commands: Command[] = [
  { command: "ls", description: "List directory contents" },
  { command: "cd", description: "Change the current directory" },
  { command: "pwd", description: "Print the current working directory" },
  { command: "mkdir", description: "Create a new directory" },
  { command: "rmdir", description: "Remove an empty directory" },
  { command: "rm", description: "Remove files or directories" },
  { command: "cp", description: "Copy files or directories" },
  { command: "mv", description: "Move or rename files or directories" },
  {
    command: "touch",
    description: "Change file timestamps or create empty files",
  },
  { command: "cat", description: "Concatenate and display file contents" },
  { command: "more", description: "View file contents one screen at a time" },
  {
    command: "less",
    description: "View file contents one screen at a time (more advanced)",
  },
  { command: "head", description: "Display the first few lines of a file" },
  { command: "tail", description: "Display the last few lines of a file" },
  { command: "grep", description: "Search for a pattern in files" },
  { command: "find", description: "Search for files and directories" },
  { command: "locate", description: "Find files by name" },
  { command: "which", description: "Locate a command" },
  { command: "man", description: "Display the manual for a command" },
  { command: "chmod", description: "Change file permissions" },
  { command: "chown", description: "Change file ownership" },
  { command: "chgrp", description: "Change group ownership of files" },
  { command: "ps", description: "Show information about running processes" },
  {
    command: "top",
    description: "Display dynamic real-time information about processes",
  },
  { command: "kill", description: "Terminate a process by its ID" },
  { command: "killall", description: "Terminate processes by name" },
  { command: "df", description: "Display disk space usage" },
  { command: "du", description: "Display disk usage of files and directories" },
  { command: "free", description: "Display memory usage" },
  {
    command: "uptime",
    description: "Show how long the system has been running",
  },
  { command: "who", description: "Show who is logged in" },
  {
    command: "w",
    description: "Show who is logged in and what they are doing",
  },
  { command: "date", description: "Display or set the system date and time" },
  {
    command: "time",
    description: "Measure the time a command takes to execute",
  },
  { command: "tar", description: "Archive files" },
  { command: "gzip", description: "Compress files using the gzip algorithm" },
  { command: "gunzip", description: "Decompress files compressed with gzip" },
  { command: "zip", description: "Create a zip archive" },
  { command: "unzip", description: "Extract files from a zip archive" },
  { command: "wget", description: "Download files from the web" },
  { command: "curl", description: "Transfer data from or to a server" },
  { command: "ssh", description: "Securely connect to a remote server" },
  { command: "scp", description: "Copy files between hosts over SSH" },
  {
    command: "rsync",
    description: "Synchronize files and directories between two locations",
  },
  {
    command: "alias",
    description: "Create custom shortcuts for commands",
    content: "content/alias.md",
  },
  { command: "unalias", description: "Remove aliases" },
  { command: "history", description: "Show command history" },
  { command: "clear", description: "Clear the terminal screen" },
  { command: "exit", description: "Exit the current shell session" },
  {
    command: "sudo",
    description: "Execute a command as another user (usually root)",
  },
  { command: "su", description: "Switch to another user account" },
  { command: "whoami", description: "Display the current logged-in user" },
  { command: "id", description: "Show user and group ID information" },
  { command: "uptime", description: "Show system uptime" },
  { command: "dmesg", description: "Print kernel messages" },
  { command: "sysctl", description: "Get or set kernel parameters at runtime" },
  { command: "mount", description: "Mount a file system" },
  { command: "umount", description: "Unmount a file system" },
  { command: "fdisk", description: "Partition table manipulator for Linux" },
  { command: "lsblk", description: "List information about block devices" },
  { command: "lspci", description: "List PCI devices" },
  { command: "lsusb", description: "List USB devices" },
  { command: "top", description: "Show Linux processes" },
  { command: "htop", description: "Interactive process viewer" },
  { command: "ps", description: "Display information about active processes" },
  { command: "kill", description: "Send a signal to terminate a process" },
];
