import { Command } from "./types";

export const commands: Command[] = [
  {
    command: "ls",
    description: "List directory contents",
    content: "/content/ls.md",
    difficulty: "Beginner",
  },
  {
    command: "cd",
    description: "Change the current directory",
    content: "/content/cd.md",
    difficulty: "Beginner",
  },
  {
    command: "pwd",
    description: "Print the current working directory",
    content: "/content/pwd.md",
    difficulty: "Beginner",
  },
  {
    command: "mkdir",
    description: "Create a new directory",
    content: "/content/mkdir.md",
    difficulty: "Beginner",
  },
  {
    command: "rmdir",
    description: "Remove an empty directory",
    content: "/content/rmdir.md",
    difficulty: "Beginner",
  },
  {
    command: "rm",
    description: "Remove files or directories",
    content: "/content/rm.md",
    difficulty: "Beginner",
  },
  {
    command: "cp",
    description: "Copy files or directories",
    content: "/content/cp.md",
    difficulty: "Beginner",
  },
  {
    command: "mv",
    description: "Move or rename files or directories",
    content: "/content/mv.md",
    difficulty: "Beginner",
  },
  {
    command: "touch",
    description: "Change file timestamps or create empty files",
    content: "/content/touch.md",
    difficulty: "Beginner",
  },
  {
    command: "cat",
    description: "Concatenate and display file contents",
    content: "/content/cat.md",
    difficulty: "Beginner",
  },
  {
    command: "more",
    description: "View file contents one screen at a time",
    content: "/content/more.md",
    difficulty: "Beginner",
  },
  {
    command: "less",
    description: "View file contents one screen at a time (more advanced)",
    content: "/content/less.md",
    difficulty: "Intermediate",
  },
  {
    command: "head",
    description: "Display the first few lines of a file",
    content: "/content/head.md",
    difficulty: "Beginner",
  },
  {
    command: "tail",
    description: "Display the last few lines of a file",
    content: "/content/tail.md",
    difficulty: "Beginner",
  },
  {
    command: "grep",
    description: "Search for a pattern in files",
    content: "/content/grep.md",
    difficulty: "Intermediate",
  },
  {
    command: "find",
    description: "Search for files and directories",
    content: "/content/find.md",
    difficulty: "Intermediate",
  },
  {
    command: "locate",
    description: "Find files by name",
    content: "/content/locate.md",
    difficulty: "Beginner",
  },
  {
    command: "which",
    description: "Locate a command",
    content: "/content/which.md",
    difficulty: "Beginner",
  },
  {
    command: "man",
    description: "Display the manual for a command",
    content: "/content/man.md",
    difficulty: "Beginner",
  },
  {
    command: "chmod",
    description: "Change file permissions",
    content: "/content/chmod.md",
    difficulty: "Intermediate",
  },
  {
    command: "chown",
    description: "Change file ownership",
    content: "/content/chown.md",
    difficulty: "Intermediate",
  },
  {
    command: "chgrp",
    description: "Change group ownership of files",
    content: "/content/chgrp.md",
    difficulty: "Intermediate",
  },
  {
    command: "ps",
    description: "Show information about running processes",
    content: "/content/ps.md",
    difficulty: "Intermediate",
  },
  {
    command: "top",
    description: "Display dynamic real-time information about processes",
    content: "/content/top.md",
    difficulty: "Intermediate",
  },
  {
    command: "kill",
    description: "Terminate a process by its ID",
    content: "/content/kill.md",
    difficulty: "Intermediate",
  },
  {
    command: "killall",
    description: "Terminate processes by name",
    content: "/content/killall.md",
    difficulty: "Intermediate",
  },
  {
    command: "df",
    description: "Display disk space usage",
    content: "/content/df.md",
    difficulty: "Intermediate",
  },
  {
    command: "du",
    description: "Display disk usage of files and directories",
    content: "/content/du.md",
    difficulty: "Intermediate",
  },
  {
    command: "free",
    description: "Display memory usage",
    content: "/content/free.md",
    difficulty: "Intermediate",
  },
  {
    command: "uptime",
    description: "Show how long the system has been running",
    content: "/content/uptime.md",
    difficulty: "Beginner",
  },
  {
    command: "who",
    description: "Show who is logged in",
    content: "/content/who.md",
    difficulty: "Beginner",
  },
  {
    command: "w",
    description: "Show who is logged in and what they are doing",
    content: "/content/w.md",
    difficulty: "Intermediate",
  },
  {
    command: "date",
    description: "Display or set the system date and time",
    content: "/content/date.md",
    difficulty: "Beginner",
  },
  {
    command: "time",
    description: "Measure the time a command takes to execute",
    content: "/content/time.md",
    difficulty: "Intermediate",
  },
  {
    command: "tar",
    description: "Archive files",
    content: "/content/tar.md",
    difficulty: "Advanced",
  },
  {
    command: "gzip",
    description: "Compress files using the gzip algorithm",
    content: "/content/gzip.md",
    difficulty: "Intermediate",
  },
  {
    command: "gunzip",
    description: "Decompress files compressed with gzip",
    content: "/content/gunzip.md",
    difficulty: "Intermediate",
  },
  {
    command: "zip",
    description: "Create a zip archive",
    content: "/content/zip.md",
    difficulty: "Beginner",
  },
  {
    command: "unzip",
    description: "Extract files from a zip archive",
    content: "/content/unzip.md",
    difficulty: "Beginner",
  },
  {
    command: "wget",
    description: "Download files from the web",
    content: "/content/wget.md",
    difficulty: "Intermediate",
  },
  {
    command: "curl",
    description: "Transfer data from or to a server",
    content: "/content/curl.md",
    difficulty: "Advanced",
  },

  {
    command: "ssh",
    description: "Securely connect to a remote server",
    content: "/content/ssh.md",
    difficulty: "Intermediate",
  },
  {
    command: "scp",
    description: "Copy files between hosts over SSH",
    content: "/content/scp.md",
    difficulty: "Intermediate",
  },
  {
    command: "rsync",
    description: "Synchronize files and directories between two locations",
    content: "/content/rsync.md",
    difficulty: "Intermediate",
  },
  {
    command: "alias",
    description: "Create custom shortcuts for commands",
    content: "/content/alias.md",
    difficulty: "Beginner",
  },
  {
    command: "unalias",
    description: "Remove aliases",
    content: "/content/unalias.md",
    difficulty: "Beginner",
  },
  {
    command: "history",
    description: "Show command history",
    content: "/content/history.md",
    difficulty: "Beginner",
  },
  {
    command: "clear",
    description: "Clear the terminal screen",
    content: "/content/clear.md",
    difficulty: "Beginner",
  },
  {
    command: "exit",
    description: "Exit the current shell session",
    content: "/content/exit.md",
    difficulty: "Beginner",
  },
  {
    command: "sudo",
    description: "Execute a command as another user (usually root)",
    content: "/content/sudo.md",
    difficulty: "Intermediate",
  },
  {
    command: "su",
    description: "Switch to another user account",
    content: "/content/su.md",
    difficulty: "Intermediate",
  },
  {
    command: "whoami",
    description: "Display the current logged-in user",
    content: "/content/whoami.md",
    difficulty: "Beginner",
  },
  {
    command: "id",
    description: "Show user and group ID information",
    content: "/content/id.md",
    difficulty: "Beginner",
  },
  {
    command: "dmesg",
    description: "Print kernel messages",
    content: "/content/dmesg.md",
    difficulty: "Advanced",
  },
  {
    command: "sysctl",
    description: "Get or set kernel parameters at runtime",
    content: "/content/sysctl.md",
    difficulty: "Advanced",
  },
  {
    command: "mount",
    description: "Mount a file system",
    content: "/content/mount.md",
    difficulty: "Advanced",
  },
  {
    command: "umount",
    description: "Unmount a file system",
    content: "/content/umount.md",
    difficulty: "Advanced",
  },
  {
    command: "fdisk",
    description: "Partition table manipulator for Linux",
    content: "/content/fdisk.md",
    difficulty: "Advanced",
  },
  {
    command: "lsblk",
    description: "List information about block devices",
    content: "/content/lsblk.md",
    difficulty: "Intermediate",
  },
  {
    command: "lspci",
    description: "List PCI devices",
    content: "/content/lspci.md",
    difficulty: "Intermediate",
  },
  {
    command: "lsusb",
    description: "List USB devices",
    content: "/content/lsusb.md",
    difficulty: "Intermediate",
  },
  {
    command: "htop",
    description: "Interactive process viewer",
    content: "/content/htop.md",
    difficulty: "Intermediate",
  },
  {
    command: "ps",
    description: "Display information about active processes",
    content: "/content/ps.md",
    difficulty: "Intermediate",
  },
];
